# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[v](bold green)"

[conda]
format = '[$symbol$environment](dimmed green) '

[localip]
ssh_only = true
format = "[IP:$localipv4](bold red) "
disabled = false

